### ISSUE TITLE
URI for epo:SelectionCriterion

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/ted-rdf-mapping-eforms#47]
Hello,

The URI for `epo:SelectionCriterion` contains the word `SelectionTerm` which is different from the way, for example, the URI of AwardCriterion is formed, also is an unrelated concept. We wonder if this is the wanted pattern. 

![image](https://github.com/user-attachments/assets/d3da1467-3deb-4d42-9861-2901939105d8)

**Comment by schivmeister** [comment]
Indeed, some URIs diverge from the norm in order to provide a more understandable hint or context for the type of instance it represents (where the type itself may not be enough hint). Quoting from the URI policy:

> Whether a concept is an ontology fragment or source element label, and whether this label has a suffix (rarely) or prefix, depends on the subjective (human) evaluation of whether only having the class name is sufficient hint of what the URI represents.

However, in this case, we note that the name used does not refer to either the XML element or the ePO class (it is not a suffix or prefix). If, given the above justification, `SelectionTerm` or any alternative does not make more sense than the ePO class, we can agree to change it. In that case, please confirm that there is no preference for an alternative name.

**Comment by cristianvasquez** [comment]
Hello, thanks for the explanation. 

The issue was raised because the name 'SelectionTerm' is different from what Business understands. I marked this as `URI patterns` to be analyzed in possible extensions of the URI policy.

**Comment by schivmeister** [comment]
We will resolve this in this iteration.
