### ISSUE TITLE
cac:PlannedPeriod and cac:ContractExtension not found

### ISSUE THREAD

**Issue by OceaneAbrard** [OP-TED/ted-rdf-mapping-eforms#67]
Issue: 
Problem with cac:PlannedPeriod and cac:ContractExtension metadata that are not mapped in a few notices of the SDKv1.7 only. The metadata is present in the xml notices, but not in the resulting ttl ones for the following references:

00126868-2024 (eFormSubType 20) missing cac:PlannedPeriod + cac:ContractExtension
00139066-2024 (eFormSubType 14) missing cac:PlannedPeriod
00143262-2024 (eFormSubType 21) missing cac:PlannedPeriod + cac:ContractExtension

For example, this is what is present in the xml of the 00126868-2024 notice (eFormSubType 20), which I can't find in the ttl.
```

        <cac:PlannedPeriod>
            <cbc:DurationMeasure unitCode="MONTH">**24**</cbc:DurationMeasure>
        </cac:PlannedPeriod>
        <cac:ContractExtension>
            <cbc:MaximumNumberNumeric>**1**</cbc:MaximumNumberNumeric>
            <cac:Renewal>
                <cac:Period>
                    <cbc:Description languageID="SPA">se prevé una prórroga de 12 meses</cbc:Description>
                </cac:Period>
            </cac:Renewal>
        </cac:ContractExtension>
```

(Issue posted upon Cristian's request)

**Comment by schivmeister** [comment]
The data elements you cite for the given example data file are at the following XPaths:

**cac:PlannedPeriod**
```xquery
/ContractNotice/cac:ProcurementProject/cac:PlannedPeriod
```

**cac:ContractExtension**
```xquery
/ContractNotice/cac:ProcurementProject/cac:ContractExtension
```

I was not able to find this in the eForms SDK `fields.json` or documented anywhere else.

**Comment by csnyulas** [comment]
Indeed, the only nodes that have `cac:PlannedPeriod` in their XPath are:
- `ND-LotDuration`, with absolute XPath  `/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:PlannedPeriod`, and
- `ND-PartDuration`, with absolute XPath `/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Part']/cac:ProcurementProject/cac:PlannedPeriod`

and the only node that has the `cac:ContractExtension` in its XPath is:
- `ND-OptionsAndRenewals`, with absolute XPath `/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:ContractExtension`

As you can see, in these nodes (and their children fields) the `cac:ProcurementProject` element should be placed under a `cac:ProcurementProjectLot` element, not directly under the root element, as it is the case in all the above notices. Apparently the notices you found are not well formed. I understood that there are more problems with the transformation of SDK v1.7 notices. Perhaps this is because in that SDK version the validators were not that advanced and were unable to catch many of the errors in the data.

**Comment by csnyulas** [comment]
Can we close this issue? Or do we want to turn it into an eForms SDK (validator) issue? Or are there other plans or solutions for dealing with wrong data?
